### ISSUE TITLE
Authentication Error

### ISSUE THREAD

**Issue by ztoolson** [mmmries/oprah#1]
Haven't looked into the reason why, the logout button isn't actually logging people out.

Steps to Reproduce.
1. Login
2. Logout
3. Click on someone to nominate
4. Magically you are signed back in

**Comment by jjcarstens** [comment]
I'm going to guess because we are OAUTH through github and our github session is still saved in the browser..

When "logout" and then clicking somewhere else you can actually watch it redirect a few times getting that from github

**Comment by mmmries** [comment]
Step 4 is actually redirecting you back to `git.moneydesktop.com` which just redirects back to `oprah` again and says, "yep, this is zach".

So you are actually still logged in since you told github to allow oprah to authenticate you.
